test: fix pytest crash
Unsure what's different that causes this, but I tried to run tests in
a new environment and received the following error:

    ValueError: test/rfc7208-tests-0_toolonglabel is not a normalized
    and relative path